[App1]
ID=1
Icon=../AutoManager/logo.png
Name=AutoM
Path=../AutoManager/AutoM

[App2]
ID=2
Icon=../Timer/logo.png
Name=Timer
Path=../Timer/Timer

[App3]
ID=3
Icon=../GPIO/logo.png
Name=GPIO
Path=../GPIO/GPIO

[App4]
ID=4
Icon=../Key/logo.png
Name=Key
Path=../Key/Key

[App5]
ID=5
Icon=../Sensor/logo.png
Name=Sensor
Path=../Sensor/Sensor

[App6]
ID=6
Icon=../Wifi/logo.png
Name=Wifi
Path=../Wifi/Wifi

[App7]
ID=7
Icon=../Mqtt/logo.png
Name=Mqtt
Path=../Mqtt/Mqtt

[AutoStart]
AutoStartID=7

[Screen]
Height=480
Width=800

[Tocken]
tocken=k9muMY12JbjaDedNPFkX
